server:
  port: 9090
spring:
  mail:
    host: smtp.qq.com
    username: 你的QQ邮箱账号
    password: 你的QQ邮箱授权密码
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      starttls:
      enable: true
      required: true
  security:
    user:
      name: admin
      password: admin
      roles: SBA_ADMIN
  boot:
    admin:
      client:
        instance:
          metadata:
            # 这里是我们在 client 设置安全账户信息  步骤中设置的账密            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
      notify:
        mail:
          from: 发送邮件的邮箱，上面配好的邮箱地址
          to: 接收邮件的邮箱
          # 配置是否启用邮件通知 false是不起用，可以自定义发送邮件和邮件内容
          enabled: true

logging:
  file: /application.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
